### PR TITLE
fixes react 16 breaking change

### PR DESCRIPTION
**Pull request by Jascha-Sundaresan**

### CODE REVIEW

**Comment by Jascha-Sundaresan** [comment]
I would strongly encourage going through and changing to `react-transition-group` v2's api.

here's the migration guide

https://github.com/reactjs/react-transition-group/blob/master/Migration.md

**Comment by nickmisasi13** [comment]
Any way we can get this merged? Trying to upgrade to React 16 and this is the only thing holding me back.

**Comment by matthieuprat** [comment]
Sorry for the delay; I wanted to test this against our main repository. Everything looks good.

@Jascha-Sundaresan Thanks again for contributing.

**Comment by nickmisasi13** [comment]
Thanks for merging. Although, the peer dependency of react-router 2.8.0 makes this not usable with 16 because of react-router 2.8.0's peer dependency of 14.0.0 || 15.0.0. #14 requests support for v3.0 of react-router. I'd look into doing it myself but I can't find any documentation on that upgrade process

**Comment by matthieuprat** [comment]
Indeed. @neoziro might take a shot at this in the next few weeks. We'll keep you posted.

**Pull request merged**
